# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/134xciAhuj1qVS2OsspKKDXTod5WBLQWq
"""

import pandas as pd
from employee_analysis import load_data, clean_data, calculate_average_salary, find_employees_with_experience, get_department_statistics

# Load data from CSV file
file_path = "/content/drive/MyDrive/Python/employees1.csv"
df = load_data(file_path)

# Clean the data
df = clean_data(df)

# Calculate average salary for a department
department = 'Engineering'
average_salary = calculate_average_salary(df, department)
if average_salary is not None:
    print(f"Average salary for {department}: ${average_salary:.2f}")

# Find employees with at least 5 years of experience
years = 5
experienced_employees = find_employees_with_experience(df, years)
if not experienced_employees.empty:
    print("\nEmployees with at least 5 years of experience:")
    print(experienced_employees[['FirstName', 'LastName']])

# Get department statistics
department_stats = get_department_statistics(df)
print("\nDepartment statistics:")
for department, stats in department_stats.items():
    print(f"Department: {department}")
    print(f"Average Salary: ${stats['Average Salary']:.2f}")
    print(f"Average Age: {stats['Average Age']:.2f} years")